allowBuilds:
    esbuild: true
    sharp: true
minimumReleaseAge: 60
minimumReleaseAgeExclude:
    - astro@6.4.5
    - "@astrojs/internal-helpers@0.10.1"
    - "@astrojs/markdown-satteri@0.3.3"
    - "@astrojs/vercel@11.0.2"
    - astro@7.0.6
